# JQDSounds Config
# To modify the sounds, simply change the name of the sound you want.

# Available Sounds:
# EndermanTeleport - Pop - AnvilFall - Bat - BlazeShoot - Door - Fizz - Ghast

Join: Pop

Quit: EndermanTeleport

Death: AnvilFall
